#undef MATRIX_ROW_PINS
#undef MATRIX_COL_PINS
#undef DIODE_DIRECTION

#define DIODE_DIRECTION ROW2COL
#define MATRIX_ROW_PINS { A2, A1, A0, B8, B13, B14 }
#define MATRIX_COL_PINS { B5, B4, B3, B2, B1, B0 }
