#ifdef MATRIX_ROW_PIN_DEFINE
MATRIX_ROW_PIN_DEFINE(0, D4)
MATRIX_ROW_PIN_DEFINE(1, C6)
MATRIX_ROW_PIN_DEFINE(2, D7)
MATRIX_ROW_PIN_DEFINE(3, E6)
MATRIX_ROW_PIN_DEFINE(4, B4)
#endif

#ifdef MATRIX_COL_PORT_DEFINE
MATRIX_COL_PORT_DEFINE(F0)
MATRIX_COL_PORT_DEFINE(B0)
#endif

#ifdef MATRIX_COL_PIN_DEFINE
MATRIX_COL_PIN_DEFINE(0, F4, F0)
MATRIX_COL_PIN_DEFINE(1, F5, F0)
MATRIX_COL_PIN_DEFINE(2, F6, F0)
MATRIX_COL_PIN_DEFINE(3, F7, F0)
MATRIX_COL_PIN_DEFINE(4, B1, B0)
MATRIX_COL_PIN_DEFINE(5, B3, B0)
#endif

#undef MATRIX_ROW_PIN_DEFINE
#undef MATRIX_COL_PORT_DEFINE
#undef MATRIX_COL_PIN_DEFINE
